name: Lint & Build Test

on:
  push:
  pull_request:
  merge_group:
    types: [checks_requested]
  
permissions:
  read-all

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: "sh -c 'cd backend && bun install'"
      - run: "sh -c 'cd backend && bun run lint'"

  format_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: "sh -c 'cd frontend && bun install'"
      - run: "sh -c 'cd frontend && bun run prettier . --check'"

  format_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: "sh -c 'cd backend && bun install'"
      - run: "sh -c 'cd backend && bun run prettier . --check'"

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: "sh -c 'cd frontend && bun install'"
      - run: "sh -c 'cd frontend && bun run build'"

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: "sh -c 'cd backend && bun install'"
      - run: "sh -c 'cd backend && bun run build'"

